"""Add image_url to Article model

Revision ID: 68c442e9a7ae
Revises: 30ede6c946bd
Create Date: 2024-12-08 15:57:59.395336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c442e9a7ae'
down_revision = '30ede6c946bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
