"""Edit Quiz model to include date_generated

Revision ID: 6eb6ffaceee1
Revises: fa684262f541
Create Date: 2024-11-11 15:47:29.822805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb6ffaceee1'
down_revision = 'fa684262f541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_generated', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('date_generated')

    # ### end Alembic commands ###
